import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.background },
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  form: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: colors.card,
    padding: 24,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 24,
    textAlign: 'center',
  },
  subtitle: { color: colors.muted, textAlign: 'center', marginBottom: 16 },
  input: {
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    color: colors.text,
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  button: {
    width: '100%',
    height: 48,
    backgroundColor: colors.primary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  buttonText: { color: colors.primaryText, fontSize: 16, fontWeight: '600' },
  row: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  rowText: { color: colors.text },
  link: { color: colors.primary, fontWeight: '600' },
  linkRight: { color: colors.primary, textAlign: 'right' },
  center: { textAlign: 'center' },
  message: { padding: 10, borderRadius: 8, marginBottom: 16, textAlign: 'center' },
  ok: { backgroundColor: colors.successBg, color: colors.successText },
  error: { backgroundColor: colors.errorBg, color: colors.errorText },
});